### ISSUE TITLE
PyPI Outdated

### ISSUE THREAD

**Issue by Orgjvr** [electronicayciencia/EasyMCP2221#18]
I would like to use the serial number when connecting to SMBus, as I have more than one bus active at a time. I made the changes required and when I wanted to create a PR, I discovered that the latest smbus.py already has all the changes needed.

As there was no new tagged version released after the fixes for the serial number, no new build were done. 

Can we get a new tagged release onto PyPI?

**Comment by electronicayciencia** [comment]
Done! Thank you for the reminder.
Please check v1.8.1.
