### ISSUE TITLE
 The library does not work on Raspberry Pi with the Raspbian operating system

### ISSUE THREAD

**Issue by z1mEk** [electronicayciencia/EasyMCP2221#5]
When creating an instance with mcp = EasyMCP2221.Device(), an error occurs:

`import EasyMCP2221

mcp = EasyMCP2221.Device()
print(f"mcp: {mcp}")

Traceback (most recent call last):
  File "/home/pi/CamPanel2/mcpTest.py", line 3, in <module>
    mcp = EasyMCP2221.Device()
  File "/home/pi/.local/lib/python3.9/site-packages/EasyMCP2221/MCP2221.py", line 106, in __init__
    self.hidhandler.open_path(hid.enumerate(self.VID, self.PID)[self.devnum]["path"])
  File "hid.pyx", line 157, in hid.device.open_path
OSError: open failed`

The same script works correctly on Windows.

**Comment by z1mEk** [comment]
I added an entry in the /etc/udev/rules.d/99-com.rules file

SUBSYSTEM=="usb", ATTRS{idVendor}=="04d8", MODE="0666", GROUP="users"

And now it works, it's probably about permissions.

**Comment by z1mEk** [comment]
Solution above.

**Comment by electronicayciencia** [comment]
Hello. This issue is documented here: [Open failed for non-root users (Linux)](https://easymcp2221.readthedocs.io/en/latest/install.html#open-failed-for-non-root-users-linux).
I'm glad you made it work!
