### ISSUE TITLE
unsaved_SRAM and status dicts are  shared by all instances

### ISSUE THREAD

**Issue by chrisjbillington** [electronicayciencia/EasyMCP2221#9]
The `Device.unsaved_SRAM` and `Device.status` dictionaries are class attributes shared by all instances. Since they're mutable, this means multiple instances are actually modifying and reading the same dictionaries, leading to incorrect behaviour when talking to two MCP2221s from the same Python process.

This can be fixed by simply by assigning these two dicts as instance attributes `self.unsaved_SRAM` and `self.status` in `__init__` instead of at the class level.

**Comment by electronicayciencia** [comment]
Hello.

AFAIK class variables need to be addressed with the Class name, like this:

```python
class c:
    foo = 1

    def __init__(self):
        self.bar = 1

    def __str__(self):
        return "foo: %d   bar: %d" % (c.foo, self.bar)

    def incr(self):
        self.bar = self.bar + 1
        c.foo = c.foo + 1

c1 = c()
c2 = c()

print(c1)
print(c2)
c1.incr()
print(c1)
print(c2)
```

After call c1.incr(), both "foo" values do increase:
```
foo: 1   bar: 1
foo: 1   bar: 1
foo: 2   bar: 2
foo: 2   bar: 1
```

But, as long as you address `foo` via self, it will be an instance variable:

```python
class c:
    foo = 1

    def __init__(self):
        self.bar = 1

    def __str__(self):
        return "foo: %d   bar: %d" % (self.foo, self.bar)

    def incr(self):
        self.bar = self.bar + 1
        self.foo = self.foo + 1

c1 = c()
c2 = c()

print(c1)
print(c2)
c1.incr()
print(c1)
print(c2)
```

Result: only c1's foo have been inrceased:

```
foo: 1   bar: 1
foo: 1   bar: 1
foo: 2   bar: 2
foo: 1   bar: 1
```

I can manage multiple MCP2221 at the same time with no problem:

![image](https://github.com/electronicayciencia/EasyMCP2221/assets/25570206/c0da5e94-e2a0-477a-ac5f-bcb0fc975e15)

Please, could you elaborate your issue with a code example?

Thank you.

**Comment by chrisjbillington** [comment]
> AFAIK class variables need to be addressed with the Class name, like this:

This is correct if you're talking about modifying *immutable* types as with your example with integers, since immutable types can't actually be modified, only be reassigned. So when you access and reassign the attribute via the instance, you're actually just creating a new instance attribute and not changing the class attribute. So there's no problem with all the immutable class attributes in the `MCP2221.Device` class.

However, for mutable datatypes such as dictionaries, the situation is different. They can be modified without being reassigned, whether they are accessed via the instance or the class:
```python
class c:
    x = {'value': 0}
    def __init__(self):
       self.x['value'] += 1
       print(self.x['value'])

c()
c()
c()
c()
```
```
1
2
3
4
```

This problem is similar to use of mutable default function arguments in Python. Mutable class attributes should be avoided unless you actually do want them to be shared by all instances.

I don't have an example of incorrect behaviour since I don't really know what these dicts are used for, but if they're used for anything important then I'm sure there is incorrect behaviour somewhere, since there is only one of each of `unsaved_SRAM` and `status` dictionary shared by all instances. I don't have access to hardware at the moment to test, but if you instantiate two MCP2221s in the same Python process and print their "status" dictionaries, you will find that they are the same.

**Comment by electronicayciencia** [comment]
You are right. Thank you. I moved these variables to the init function. Happy to learn something new today.
